### ISSUE TITLE
Specify contentType when making ajax call:

### ISSUE THREAD

**Issue by saadrizvi** [jacobscarter/angular-feedback#8]
Currently you have the ajax call without declaring a contentType. 

`contentType : 'application/json',`

**Comment by saadrizvi** [comment]
Also, why is it `var data = {feedback: JSON.stringify(post)};` as opposted to `var data = JSON.stringify(post);` Any particular reason?

**Comment by jacobscarter** [comment]
Hi @saadrizvi in order to avoid merge conflicts I made your changes in another commit and will close your PR.  In regard to your questions about have an object with feedback property, no particular reason, but I think it is just as arbitrary and not having an object, so I will leave it until a valid reason to change it comes to light.  Updates available in 1.1.0

**Comment by gulfaraz** [comment]
This change causes a **400 Bad Request** on my api call. Removing `contentType : 'application/json'` fixed the issue - is there any other change I need to do to make this work with `contentType` ?
